require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Severity: error

  Exclude:
    - "node_modules/**/*"
    - "bin/**/*"
    - "vendor/**/*"

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "config/environments/**/*.rb"

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*.rb"

Rails/FilePath:
  EnforcedStyle: arguments

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
