require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Severity: error

  Exclude:
    - "bin/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100

Lint/ScriptPermission:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*_spec.rb"
    - "config/environments/**/*.rb"

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 10
  Exclude:
    - "db/migrate/**/*.rb"

Rails/FilePath:
  EnforcedStyle: arguments

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
